### ISSUE TITLE
Library Version

### ISSUE THREAD

**Issue by TomShkurti** [lucasw/vimjay#12]
Is this still active? It'd be great if it offered up some of its functionality that's generally useful, like the initDistortMap() function, as part of a library that could be used in other code through catkin. Maybe this is already possible and I just don't know how to do it, but ordinarily I think you'd need to have "LIBRARIES vimjay" uncommented in your package description as well as actually compiling the code as a library and possibly other changes) to do that.

**Comment by lucasw** [comment]
It's not completely inactive, I try to keep it parts of it compiling, but at the same time I've moved or re-implemented some of the more useful code to https://github.com/lucasw/image_manip including `initDistortMaps()`, which is built into a library (along with some nodelets).  Does that work for you?

**Comment by TomShkurti** [comment]
Perfectly.
